const companies = [
  {
    "id": 1,
    "stir": "308572034",
    "name": "\"ALMALYK QUYUV MEXANIKA ZAVODI\" MCHJ",
    "viloyat": "Тошкент вилояти",
    "tuman": "Олмалиқ шаҳри",
    "sector": "Тоғ-кон, геология, металургия саноати",
    "mahsulot": "Оғир тоғ-кон саноати машиналари ва ускуналари учун эҳтиёт қисмлар",
    "stend": "Стандарт",
    "area": 9,
    "contact": "",
    "phone": "90-188-03-03",
    "mapX": 350,
    "mapY": 230,
    "parent_org_stirs": [
      "308425864"
    ],
    "parent_org_name": "\"Olmaliq KMK\" AJ",
    "tip": "Шатак",
    "supplies_to": []
  },
  {
    "id": 2,
    "stir": "309793391",
    "name": "\"ANGREN PIPE PLANT\" MCHJ",
    "viloyat": "Тошкент вилояти",
    "tuman": "Оҳангарон тумани",
    "sector": "Тоғ-кон, геология, металургия саноати",
    "mahsulot": "Мис қувурларини ишлаб чиқариш",
    "stend": "Стандарт",
    "area": 9,
    "contact": "Директор Алишер ака",
    "phone": "93-182-58-81",
    "mapX": 449,
    "mapY": 256,
    "parent_org_stirs": [
      "308425864"
    ],
    "parent_org_name": "\"Olmaliq KMK\" AJ",
    "tip": "Шатак",
    "supplies_to": [
      "202328794"
    ],
    "tarmoq": "\"Ўзэлтехсаноат\" уюшмаси",
    "xabardor": "ха",
    "tovar_soni": "15",
    "takliflar_sectors": "НКМК",
    "ishtirokchi": "Директор ва технолог",
    "izoh": "12 май куни маҳсулотларни етказади"
  },
  {
    "id": 3,
    "stir": "309450390",
    "name": "DEUTSCHE INNOVATSION TEXNOLOGIYALAR-AGMK",
    "viloyat": "Андижон вилояти",
    "tuman": "Олмалиқ шаҳри",
    "sector": "Sanoat",
    "mahsulot": "Композит-полимер материаллар",
    "stend": "Стандарт",
    "area": 9,
    "contact": "",
    "phone": "97-440-98-77",
    "mapX": 511,
    "mapY": 326,
    "parent_org_stirs": [
      "308425864"
    ],
    "parent_org_name": "\"Olmaliq KMK\" AJ",
    "tip": "Шатак",
    "supplies_to": []
  },
  {
    "id": 4,
    "stir": "205778597",
    "name": "\"KURAMA-VOSTOK\" ХК",
    "viloyat": "Тошкент вилояти",
    "tuman": "Олмалиқ шаҳри",
    "sector": "Тоғ-кон, геология, металургия саноати",
    "mahsulot": "Махсус иш кийимлари",
    "stend": "Стандарт",
    "area": 9,
    "contact": "Директор Алишер ака",
    "phone": "93-182-65-18",
    "mapX": 511,
    "mapY": 413,
    "parent_org_stirs": [
      "308425864"
    ],
    "parent_org_name": "\"Olmaliq KMK\" AJ",
    "tip": "Шатак",
    "supplies_to": [
      "202328794"
    ],
    "tarmoq": "\"Ўзтўқимачиликсаноат\" уюшмаси",
    "xabardor": "ха",
    "tovar_soni": "30",
    "takliflar_sectors": "Биржадаги муаммолар",
    "ishtirokchi": "Директор ва технолог",
    "izoh": "12 май куни маҳсулотларни етказади"
  },
  {
    "id": 5,
    "stir": "306167934",
    "name": "\"NURAFSHON-MAXSUS-TEXNIKA\" MCHJ",
    "viloyat": "Тошкент вилояти",
    "tuman": "Нурафшон шаҳри",
    "sector": "Тоғ-кон, геология, металургия саноати",
    "mahsulot": "Карер самосвали",
    "stend": "Стандарт",
    "area": 9,
    "contact": "",
    "phone": "97-740-00-26",
    "mapX": 449,
    "mapY": 483,
    "parent_org_stirs": [
      "308425864"
    ],
    "parent_org_name": "\"Olmaliq KMK\" AJ",
    "tip": "Шатак",
    "supplies_to": []
  },
  {
    "id": 6,
    "stir": "306136027",
    "name": "\"DRILL-FLOT ASIA\" MCHJ",
    "viloyat": "Тошкент вилояти",
    "tuman": "Ангрен шаҳри",
    "sector": "Тоғ-кон, геология, металургия саноати",
    "mahsulot": "Юқори босимли шланглар",
    "stend": "Стандарт",
    "area": 9,
    "contact": "Абдураупова Г.М.",
    "phone": "90-952-23-32",
    "mapX": 350,
    "mapY": 510,
    "parent_org_stirs": [
      "308425864"
    ],
    "parent_org_name": "\"Olmaliq KMK\" AJ",
    "tip": "Шатак",
    "supplies_to": []
  },
  {
    "id": 7,
    "stir": "200240345",
    "name": "“ANDIJON YUK VAGONLARINI QURISH VA TA’MIRLASH ZAVODI” MCHJ",
    "viloyat": "Тошкент вилояти",
    "tuman": "Олмалиқ шаҳри",
    "sector": "Sanoat",
    "mahsulot": "Янги 4 ўқли сулфат киспотаси ташиш учун мўлжаланган вагон систерна",
    "stend": "Стандарт",
    "area": 9,
    "contact": "Б.Б.Усманов",
    "phone": "933814411, 934100201, 934109030",
    "mapX": 250,
    "mapY": 483,
    "parent_org_stirs": [
      "308425864"
    ],
    "parent_org_name": "\"Olmaliq KMK\" AJ",
    "tip": "Шатак",
    "supplies_to": [
      "201051951",
      "202328794",
      "308425864",
      "201204514",
      "207321659"
    ],
    "tarmoq": "\"Ўзбекистон темир йўллари\" АЖ",
    "xabardor": "Bor",
    "tovar_soni": "banner prezentasiya",
    "takliflar_sectors": "Sho'rtangaz kimyo sanoat",
    "ishtirokchi": "tashqi iqtisodiy aloqalar marketingi va tayyor mahsulotlar sotish bo'limi",
    "izoh": "Hududgaz ta'minot bilan ishlarni davom etish"
  },
  {
    "id": 8,
    "stir": "305913917",
    "name": "\"RIALWAY SERVICE\" MCHJ",
    "viloyat": "Тошкент вилояти",
    "tuman": "Ангрен шаҳри",
    "sector": "Тоғ-кон, геология, металургия саноати",
    "mahsulot": "Темир йўл учун эҳтиёт қисмлар",
    "stend": "Стандарт",
    "area": 9,
    "contact": "Газибеков М.Ш.",
    "phone": "99-825-43-50",
    "mapX": 188,
    "mapY": 413,
    "parent_org_stirs": [
      "308425864"
    ],
    "parent_org_name": "\"Olmaliq KMK\" AJ",
    "tip": "Шатак",
    "supplies_to": []
  },
  {
    "id": 9,
    "stir": "204608594",
    "name": "\"IGEA\" MCHJ QK",
    "viloyat": "Тошкент вилояти",
    "tuman": "Олмалиқ шаҳри",
    "sector": "Тоғ-кон, геология, металургия саноати",
    "mahsulot": "Тоғ-кон ускуналари",
    "stend": "Стандарт",
    "area": 9,
    "contact": "",
    "phone": "+998 94 379 05 65",
    "mapX": 188,
    "mapY": 326,
    "parent_org_stirs": [
      "308425864"
    ],
    "parent_org_name": "\"Olmaliq KMK\" AJ",
    "tip": "Шатак",
    "supplies_to": [],
    "tarmoq": "\"Ўзтўқимачиликсаноат\" уюшмаси",
    "xabardor": "",
    "tovar_soni": "",
    "takliflar_sectors": "",
    "ishtirokchi": "",
    "izoh": "ўчиқ"
  },
  {
    "id": 10,
    "stir": "204608594",
    "name": "\"APITEKS\" MCHJ",
    "viloyat": "Тошкент вилояти",
    "tuman": "Оҳангарон тумани",
    "sector": "Тоғ-кон, геология, металургия саноати",
    "mahsulot": "Филтр матолар",
    "stend": "Стандарт",
    "area": 9,
    "contact": "",
    "phone": "90-939-15-58",
    "mapX": 250,
    "mapY": 256,
    "parent_org_stirs": [
      "308425864"
    ],
    "parent_org_name": "\"Olmaliq KMK\" AJ",
    "tip": "Шатак",
    "supplies_to": [],
    "tarmoq": "\"Ўзтўқимачиликсаноат\" уюшмаси",
    "xabardor": "",
    "tovar_soni": "",
    "takliflar_sectors": "",
    "ishtirokchi": "",
    "izoh": "ўчиқ"
  },
  {
    "id": 11,
    "stir": "205734367",
    "name": "\"CARBON POLYMER\" MCHJ",
    "viloyat": "Тошкент вилояти",
    "tuman": "Олмалиқ шаҳри",
    "sector": "Тоғ-кон, геология, металургия саноати",
    "mahsulot": "Фторопласт маҳсулотлар ва эҳтиёт қисмлар",
    "stend": "Эксклюзив",
    "area": 27,
    "contact": "",
    "phone": "95-171-99-00",
    "mapX": 430,
    "mapY": 430,
    "parent_org_stirs": [
      "308425864"
    ],
    "parent_org_name": "\"Olmaliq KMK\" AJ",
    "tip": "Кооперация",
    "supplies_to": []
  },
  {
    "id": 12,
    "stir": "305640387",
    "name": "\"FERRUM\" MCHJ",
    "viloyat": "Тошкент вилояти",
    "tuman": "Ангрен шаҳри",
    "sector": "Тоғ-кон, геология, металургия саноати",
    "mahsulot": "Пўлатдан ишлов берилган тайёр маҳсулотлар",
    "stend": "Стандарт",
    "area": 9,
    "contact": "Газибеков М.Ш.",
    "phone": "99-825-43-50",
    "mapX": 564,
    "mapY": 460,
    "parent_org_stirs": [
      "308425864"
    ],
    "parent_org_name": "\"Olmaliq KMK\" AJ",
    "tip": "Кооперация",
    "supplies_to": []
  },
  {
    "id": 13,
    "stir": "301643299",
    "name": "\"PISKENT HAMKOR SAVDO\" MCHJ",
    "viloyat": "Тошкент вилояти",
    "tuman": "Пискент тумани",
    "sector": "Тоғ-кон, геология, металургия саноати",
    "mahsulot": "Оловдан ҳимояловчи (ЎП) сингдирма билан ишлов берилган брезент (парусина) мато",
    "stend": "Стандарт",
    "area": 9,
    "contact": "",
    "phone": "97-777-96-77",
    "mapX": 636,
    "mapY": 537,
    "parent_org_stirs": [
      "308425864"
    ],
    "parent_org_name": "\"Olmaliq KMK\" AJ",
    "tip": "Кооперация",
    "supplies_to": []
  },
  {
    "id": 14,
    "stir": "206127424",
    "name": "\"NASIBA-GAVHAR\" XK",
    "viloyat": "Тошкент вилояти",
    "tuman": "Пискент тумани",
    "sector": "Тоғ-кон, геология, металургия саноати",
    "mahsulot": "Текстил матолар",
    "stend": "Стандарт",
    "area": 9,
    "contact": "Мирахмедов Нодир",
    "phone": "97-777-96-77",
    "mapX": 611,
    "mapY": 625,
    "parent_org_stirs": [
      "308425864"
    ],
    "parent_org_name": "\"Olmaliq KMK\" AJ",
    "tip": "Кооперация",
    "supplies_to": [
      "202328794"
    ],
    "tarmoq": "\"Ўзтўқимачиликсаноат\" уюшмаси",
    "xabardor": "ха",
    "tovar_soni": "20",
    "takliflar_sectors": "НКМК, Ўзбекнефтигаз, Худудгаз",
    "ishtirokchi": "Директор ва технолог",
    "izoh": "12 май куни маҳсулотларни етказади"
  },
  {
    "id": 15,
    "stir": "202610025",
    "name": "\"SANOAT OGNEUPOR VA BUTLOV\" MCHJ",
    "viloyat": "Тошкент вилояти",
    "tuman": "Олмалиқ шаҳри",
    "sector": "Тоғ-кон, геология, металургия саноати",
    "mahsulot": "Олов бардош маҳсулотлар",
    "stend": "Стандарт",
    "area": 9,
    "contact": "",
    "phone": "90-123-55-27",
    "mapX": 501,
    "mapY": 682,
    "parent_org_stirs": [
      "308425864"
    ],
    "parent_org_name": "\"Olmaliq KMK\" AJ",
    "tip": "Кооперация",
    "supplies_to": []
  },
  {
    "id": 16,
    "stir": "301362063",
    "name": "\"NAMELEKTRO\" MCHJ",
    "viloyat": "Наманган вилояти",
    "tuman": "Давлатобод тумани",
    "sector": "Тоғ-кон, геология, металургия саноати",
    "mahsulot": "Изоляторлар",
    "stend": "Стандарт",
    "area": 9,
    "contact": "Мухитдинов А.",
    "phone": "99899 976 56 89",
    "mapX": 358,
    "mapY": 682,
    "parent_org_stirs": [
      "308425864"
    ],
    "parent_org_name": "\"Olmaliq KMK\" AJ",
    "tip": "Кооперация",
    "supplies_to": []
  },
  {
    "id": 17,
    "stir": "302985735",
    "name": "\"AUTO PAD SYSTEMS\" MCHJ",
    "viloyat": "Жиззах вилояти",
    "tuman": "Жиззах шаҳри",
    "sector": "Тоғ-кон, геология, металургия саноати",
    "mahsulot": "Тормоз колодкалари ассортименти",
    "stend": "Стандарт",
    "area": 9,
    "contact": "Мурад ака",
    "phone": "97 753 61 63",
    "mapX": 248,
    "mapY": 625,
    "parent_org_stirs": [
      "308425864"
    ],
    "parent_org_name": "\"Olmaliq KMK\" AJ",
    "tip": "Кооперация",
    "supplies_to": []
  },
  {
    "id": 18,
    "stir": "202610025",
    "name": "\"OGNEUPOR\" MCHJ",
    "viloyat": "Тошкент шаҳри",
    "tuman": "Юнусобод тумани",
    "sector": "Тоғ-кон, геология, металургия саноати",
    "mahsulot": "Оловбардош ғиштлар",
    "stend": "Стандарт",
    "area": 9,
    "contact": "Зодие",
    "phone": "99 644 26 71, 935558520, 909315679",
    "mapX": 223,
    "mapY": 537,
    "parent_org_stirs": [
      "308425864"
    ],
    "parent_org_name": "\"Olmaliq KMK\" AJ",
    "tip": "Кооперация",
    "supplies_to": []
  },
  {
    "id": 19,
    "stir": "311691884",
    "name": "ANDIJAN ELEKTROTEXNIKA ZAVODI MCHJ",
    "viloyat": "Андижон вилояти",
    "tuman": "Андижон шаҳри",
    "sector": "Тоғ-кон, геология, металургия саноати",
    "mahsulot": "Босим ўзгартиргичлар",
    "stend": "Стандарт",
    "area": 9,
    "contact": "Турсуналиев Сардорбек Сойибжон угли",
    "phone": "+998 33 808 29 29",
    "mapX": 295,
    "mapY": 460,
    "parent_org_stirs": [
      "308425864"
    ],
    "parent_org_name": "\"Olmaliq KMK\" AJ",
    "tip": "Кооперация",
    "supplies_to": []
  },
  {
    "id": 20,
    "stir": "300369838",
    "name": "GIDRO STANKO SERVIS MCHJ",
    "viloyat": "Навоий вилояти",
    "tuman": "Навоий шаҳар",
    "sector": "Тоғ-кон, геология, металургия саноати",
    "mahsulot": "Кон-шахта жиҳозлари, редукторлар, насослар ва эҳтиёт қисмлар",
    "stend": "Стандарт",
    "area": 9,
    "contact": "Абдуллаев А.Ф./Маликов У.М.",
    "phone": "931732896,  939510001",
    "mapX": 636,
    "mapY": 250,
    "parent_org_stirs": [
      "308425864"
    ],
    "parent_org_name": "\"Navoiy KMK\" AJ",
    "tip": "Шатак",
    "supplies_to": []
  },
  {
    "id": 21,
    "stir": "200003038",
    "name": "\"NAVOIYELEKTROREMONT\" МЧЖ",
    "viloyat": "Навоий вилояти",
    "tuman": "Навоий шаҳар",
    "sector": "Sanoat",
    "mahsulot": "Электр двигателлар ва ускуналар",
    "stend": "Стандарт",
    "area": 9,
    "contact": "",
    "phone": "792230071.0",
    "mapX": 730,
    "mapY": 272,
    "parent_org_stirs": [
      "308425864"
    ],
    "parent_org_name": "\"Navoiy KMK\" AJ",
    "tip": "Шатак",
    "supplies_to": []
  },
  {
    "id": 22,
    "stir": "300588810",
    "name": "NAVPROMLITMASH MCHJ",
    "viloyat": "Навоий вилояти",
    "tuman": "Навоий шаҳар",
    "sector": "Тоғ-кон, геология, металургия саноати",
    "mahsulot": "Кон-шахта жиҳозлари, филтрлар",
    "stend": "Стандарт",
    "area": 9,
    "contact": "Файзиев Ибрагим",
    "phone": "90-717-5454",
    "mapX": 788,
    "mapY": 332,
    "parent_org_stirs": [
      "308425864"
    ],
    "parent_org_name": "\"Navoiy KMK\" AJ",
    "tip": "Шатак",
    "supplies_to": []
  },
  {
    "id": 23,
    "stir": "300588810",
    "name": "\"UNIVERSAL FILTR\" MCHJ",
    "viloyat": "Навоий вилояти",
    "tuman": "Навоий шаҳар",
    "sector": "Sanoat",
    "mahsulot": "Хаво ва мой фильтрлари",
    "stend": "Стандарт",
    "area": 9,
    "contact": "Шерзод",
    "phone": "907310030.0",
    "mapX": 788,
    "mapY": 407,
    "parent_org_stirs": [
      "308425864"
    ],
    "parent_org_name": "\"Navoiy KMK\" AJ",
    "tip": "Шатак",
    "supplies_to": []
  },
  {
    "id": 24,
    "stir": "309084854",
    "name": "TIO PROM KOMPOZIT 2022 MCHJ",
    "viloyat": "Навоий вилояти",
    "tuman": "Навоий шаҳар",
    "sector": "Тоғ-кон, геология, металургия саноати",
    "mahsulot": "Композит қувур ва фитинглар",
    "stend": "Стандарт",
    "area": 9,
    "contact": "Файзиев Вохиджон",
    "phone": "91-338-9664",
    "mapX": 730,
    "mapY": 467,
    "parent_org_stirs": [
      "308425864"
    ],
    "parent_org_name": "\"Navoiy KMK\" AJ",
    "tip": "Шатак",
    "supplies_to": []
  },
  {
    "id": 25,
    "stir": "302684248",
    "name": "\"CHILON LUBRICANTS\" МЧЖ",
    "viloyat": "Тошкент шаҳри",
    "tuman": "Бектемир тумани",
    "sector": "Sanoat",
    "mahsulot": "Композицион мойлаш маҳсулотлари, эмульгатор ва б.",
    "stend": "Стандарт",
    "area": 9,
    "contact": "",
    "phone": "974472555.0",
    "mapX": 636,
    "mapY": 490,
    "parent_org_stirs": [
      "308425864"
    ],
    "parent_org_name": "\"Navoiy KMK\" AJ",
    "tip": "Шатак",
    "supplies_to": []
  },
  {
    "id": 26,
    "stir": "306816885",
    "name": "LATEM-METAL MCHJ",
    "viloyat": "Навоий вилояти",
    "tuman": "Навоий шаҳар",
    "sector": "Тоғ-кон, геология, металургия саноати",
    "mahsulot": "Пўлат қуймалар",
    "stend": "Стандарт",
    "area": 9,
    "contact": "",
    "phone": "97 3686611, 95 0718022",
    "mapX": 541,
    "mapY": 467,
    "parent_org_stirs": [
      "308425864"
    ],
    "parent_org_name": "\"Navoiy KMK\" AJ",
    "tip": "Шатак",
    "supplies_to": []
  },
  {
    "id": 27,
    "stir": "302744955",
    "name": "EVRO PROM LIDER MCHJ",
    "viloyat": "Тошкент шаҳри",
    "tuman": "Яшнобод тумани",
    "sector": "Тоғ-кон, геология, металургия саноати",
    "mahsulot": "Филтрловчи маҳсулотлар",
    "stend": "Стандарт",
    "area": 9,
    "contact": "Хаитов Сохибжон",
    "phone": "90-189-9426",
    "mapX": 483,
    "mapY": 407,
    "parent_org_stirs": [
      "308425864"
    ],
    "parent_org_name": "\"Navoiy KMK\" AJ",
    "tip": "Шатак",
    "supplies_to": [
      "308425864",
      "202328794",
      "311415426",
      "200460222",
      "201204514"
    ],
    "tarmoq": "\"Ўзтўқимачиликсаноат\" уюшмаси",
    "xabardor": "бор",
    "tovar_soni": "30 та саноат фильтрлари",
    "takliflar_sectors": "“O‘zsanoatqurilishmateriallari” uyushmasi, \nFarmatsevtika tarmog‘ini rivojlantirish agentligi",
    "ishtirokchi": "Иванов Аброр ва Мардор маркетолог",
    "izoh": "Корхонани хабари бор 12,05,2026 йил куни маҳсулотларни олиб боради"
  },
  {
    "id": 28,
    "stir": "206945064",
    "name": "AVTOTRAKTORRADIATOR MCHJ",
    "viloyat": "Қашқадарё вилояти",
    "tuman": "Қарши шаҳри",
    "sector": "Тоғ-кон, геология, металургия саноати",
    "mahsulot": "Техника учун радиаторлар",
    "stend": "Стандарт",
    "area": 9,
    "contact": "Рузиев Жаҳонгир  Абдирашидович",
    "phone": "97 200 00 43",
    "mapX": 483,
    "mapY": 332,
    "parent_org_stirs": [
      "308425864"
    ],
    "parent_org_name": "\"Navoiy KMK\" AJ",
    "tip": "Шатак",
    "supplies_to": [
      "308425864",
      "202328794"
    ],
    "tarmoq": "\"Ўзагротехсаноатхолдинг\" АЖ",
    "xabardor": "бор",
    "tovar_soni": "4 та катта радиаторлар",
    "takliflar_sectors": "“O‘zbekiston temir yo‘llari” AJ, \"TOSHKENT TRAKTOR ZAVODI\"  МЧЖ",
    "ishtirokchi": "Рузиев Жаҳонгир\n Абдирашидович савдо бўлими бошлиғи",
    "izoh": "Корхонани хабари бор 12,05,2026 йил куни маҳсулотларни олиб боради"
  },
  {
    "id": 29,
    "stir": "309615209",
    "name": "METALL MAHSULOT ZAVODI MCHJ",
    "viloyat": "Навоий вилояти",
    "tuman": "Кармана тумани",
    "sector": "Тоғ-кон, геология, металургия саноати",
    "mahsulot": "Металларга ишлов бериш, метиз маҳсулотлари",
    "stend": "Стандарт",
    "area": 9,
    "contact": "Роман Липкин",
    "phone": "88-460-9090",
    "mapX": 541,
    "mapY": 272,
    "parent_org_stirs": [
      "308425864"
    ],
    "parent_org_name": "\"Navoiy KMK\" AJ",
    "tip": "Шатак",
    "supplies_to": []
  },
  {
    "id": 30,
    "stir": "205652629",
    "name": "BIG PROM SERVIS MCHJ",
    "viloyat": "Навоий вилояти",
    "tuman": "Навоий шаҳар",
    "sector": "Тоғ-кон, геология, металургия саноати",
    "mahsulot": "Ҳимоя воситалари",
    "stend": "Стандарт",
    "area": 9,
    "contact": "Пармонов Алишер",
    "phone": "98-363-9944,  71-277-0102",
    "mapX": 750,
    "mapY": 450,
    "parent_org_stirs": [
      "308425864"
    ],
    "parent_org_name": "\"Navoiy KMK\" AJ",
    "tip": "Кооперация",
    "supplies_to": [
      "200837914",
      "202328794",
      "308425864"
    ],
    "tarmoq": "\"Ўзтўқимачиликсаноат\" уюшмаси",
    "xabardor": "Bor",
    "tovar_soni": "20 xildan ortiq mahsulot",
    "takliflar_sectors": "O'zkimyosanoat, Navoiyazot",
    "ishtirokchi": "Direktor + 2 ta xodim",
    "izoh": "Menga nima foyda, shartnoma bo'ladimi yo'qmi"
  },
  {
    "id": 31,
    "stir": "200000065",
    "name": "KIMYO SERVIS NAVOIY MCHJ",
    "viloyat": "Навоий вилояти",
    "tuman": "Навоий шаҳар",
    "sector": "Тоғ-кон, геология, металургия саноати",
    "mahsulot": "Оловга чидамли маҳсулотлар",
    "stend": "Стандарт",
    "area": 9,
    "contact": "",
    "phone": "97 322 71 15",
    "mapX": 853,
    "mapY": 495,
    "parent_org_stirs": [
      "308425864"
    ],
    "parent_org_name": "\"Navoiy KMK\" AJ",
    "tip": "Кооперация",
    "supplies_to": []
  },
  {
    "id": 32,
    "stir": "304777138",
    "name": "“STALMET GROUP SERVICE” MCHJ",
    "viloyat": "Тошкент шаҳри",
    "tuman": "Мирзо Улуғбек тумани",
    "sector": "Тоғ-кон, геология, металургия саноати",
    "mahsulot": "Тормоз колодкаларининг накладкалари",
    "stend": "Стандарт",
    "area": 9,
    "contact": "Ахмедов Тулкин",
    "phone": "93 577 50 45, 97 753 61 63",
    "mapX": 853,
    "mapY": 585,
    "parent_org_stirs": [
      "308425864"
    ],
    "parent_org_name": "\"Navoiy KMK\" AJ",
    "tip": "Кооперация",
    "supplies_to": []
  },
  {
    "id": 33,
    "stir": "312602374",
    "name": "«EKOLIFE» MCHJ",
    "viloyat": "Тошкент вилояти",
    "tuman": "Ангрен шаҳри",
    "sector": "Sanoat",
    "mahsulot": "Приточно – вытяжная установка с рекуператором ТЭН,УФ, Фильтр из терморасширенного пропитанного графита (ТРПГ)",
    "stend": "Стандарт",
    "area": 9,
    "contact": "Хасан (Менеджер)",
    "phone": "770470778.0",
    "mapX": 750,
    "mapY": 630,
    "parent_org_stirs": [
      "308425864"
    ],
    "parent_org_name": "\"Navoiy KMK\" AJ",
    "tip": "Кооперация",
    "supplies_to": []
  },
  {
    "id": 34,
    "stir": "301297469",
    "name": "SDK GROUP AND  MCHJ",
    "viloyat": "Фарғона вилояти",
    "tuman": "Шаҳрихон тумани",
    "sector": "Тоғ-кон, геология, металургия саноати",
    "mahsulot": "Тоғ-кон техникалар учун филтрлар ва филтрлаш элементлари",
    "stend": "Стандарт",
    "area": 9,
    "contact": "Халилов Шукрулло",
    "phone": "90 812-51-51",
    "mapX": 646,
    "mapY": 585,
    "parent_org_stirs": [
      "308425864"
    ],
    "parent_org_name": "\"Navoiy KMK\" AJ",
    "tip": "Кооперация",
    "supplies_to": []
  },
  {
    "id": 35,
    "stir": "303039540",
    "name": "GORTEHPROM MCHJ",
    "viloyat": "Фарғона вилояти",
    "tuman": "Фарғона шаҳри",
    "sector": "Тоғ-кон, геология, металургия саноати",
    "mahsulot": "Кон-металлургия, карер ускуналари ва уларнинг эҳтиёт қисмлари",
    "stend": "Стандарт",
    "area": 9,
    "contact": "Джумаматов Каримжон Турсуматович",
    "phone": "(90)230-15-51",
    "mapX": 646,
    "mapY": 495,
    "parent_org_stirs": [
      "308425864"
    ],
    "parent_org_name": "\"Navoiy KMK\" AJ",
    "tip": "Кооперация",
    "supplies_to": []
  },
  {
    "id": 36,
    "stir": "305259550",
    "name": "“WANG DA ROLLING STEEL” MCHJ",
    "viloyat": "Сирдарё вилояти",
    "tuman": "Сирдарё тумани",
    "sector": "Тоғ-кон, геология, металургия саноати",
    "mahsulot": "Узлуксиз қуйма пўлат квадрати ўлчами 150х150мм, узунлиги 4-6 метр Ст60",
    "stend": "Стандарт",
    "area": 9,
    "contact": "Расулхон, Синдор",
    "phone": "900049896, 918037673",
    "mapX": 1100,
    "mapY": 170,
    "parent_org_stirs": [
      "200460222"
    ],
    "parent_org_name": "\"O'zmetkombinat\" AJ",
    "tip": "Шатак",
    "supplies_to": []
  },
  {
    "id": 37,
    "stir": "203694539",
    "name": "BEKABAD OGNEUPOR MCHJ",
    "viloyat": "Тошкент вилояти",
    "tuman": "Бекобод шаҳри",
    "sector": "Тоғ-кон, геология, металургия саноати",
    "mahsulot": "Оловбардош маҳсулотлари",
    "stend": "Стандарт",
    "area": 9,
    "contact": "Николай Воронков",
    "phone": "90 988-44-13",
    "mapX": 1300,
    "mapY": 170,
    "parent_org_stirs": [
      "200460222"
    ],
    "parent_org_name": "\"O'zmetkombinat\" AJ",
    "tip": "Шатак",
    "supplies_to": []
  },
  {
    "id": 38,
    "stir": "302076513",
    "name": "TURON ABRASIVE MCHJ",
    "viloyat": "Тошкент шаҳри",
    "tuman": "Яшнобод тумани",
    "sector": "Тоғ-кон, геология, металургия саноати",
    "mahsulot": "қаттиқ қотишма пластиналар",
    "stend": "Стандарт",
    "area": 9,
    "contact": "",
    "phone": "946600919.0",
    "mapX": 1500,
    "mapY": 170,
    "parent_org_stirs": [
      "200460222"
    ],
    "parent_org_name": "\"O'zmetkombinat\" AJ",
    "tip": "Шатак",
    "supplies_to": []
  },
  {
    "id": 39,
    "stir": "303127424",
    "name": "\"DIZEL DETAL SAVDO\" MCHJ",
    "viloyat": "Тошкент вилояти",
    "tuman": "Юқори Чирчиқ тумани",
    "sector": "Тоғ-кон, геология, металургия саноати",
    "mahsulot": "Резина шланглар ассортименти",
    "stend": "Стандарт",
    "area": 9,
    "contact": "Матякубов А.М.",
    "phone": "94-929-48-17",
    "mapX": 1700,
    "mapY": 170,
    "parent_org_stirs": [
      "200460222"
    ],
    "parent_org_name": "\"O'zmetkombinat\" AJ",
    "tip": "Шатак",
    "supplies_to": []
  },
  {
    "id": 40,
    "stir": "300544880",
    "name": "\"NAM MOTOR SERVIS\" MCHJ",
    "viloyat": "Наманган вилояти",
    "tuman": "Наманган тумани",
    "sector": "Тоғ-кон, геология, металургия саноати",
    "mahsulot": "Энергетик маҳсулотлар",
    "stend": "Стандарт",
    "area": 9,
    "contact": "",
    "phone": "993666235, 953031020",
    "mapX": 1100,
    "mapY": 260,
    "parent_org_stirs": [
      "200460222"
    ],
    "parent_org_name": "\"O'zmetkombinat\" AJ",
    "tip": "Шатак",
    "supplies_to": []
  },
  {
    "id": 41,
    "stir": "311040919",
    "name": "UZXCMG",
    "viloyat": "Самарқанд вилояти",
    "tuman": "Нуробод тумани",
    "sector": "Тоғ-кон, геология, металургия саноати",
    "mahsulot": "Металлоконструкция",
    "stend": "Стандарт",
    "area": 9,
    "contact": "",
    "phone": "94 399 10 50",
    "mapX": 1300,
    "mapY": 260,
    "parent_org_stirs": [
      "200460222"
    ],
    "parent_org_name": "\"O'zmetkombinat\" AJ",
    "tip": "Шатак",
    "supplies_to": []
  },
  {
    "id": 42,
    "stir": "306564869",
    "name": "HYDRO COMPONENT MCHJ",
    "viloyat": "Тошкент шаҳри",
    "tuman": "Миробод тумани",
    "sector": "Тоғ-кон, геология, металургия саноати",
    "mahsulot": "Юқори босимли шланглар",
    "stend": "Стандарт",
    "area": 9,
    "contact": "",
    "phone": "94 669 08 17",
    "mapX": 1500,
    "mapY": 260,
    "parent_org_stirs": [
      "200460222"
    ],
    "parent_org_name": "\"O'zmetkombinat\" AJ",
    "tip": "Шатак",
    "supplies_to": []
  },
  {
    "id": 43,
    "stir": "203973278",
    "name": "JIHOZVENT MCHJ",
    "viloyat": "Тошкент шаҳри",
    "tuman": "Чилонзор тумани",
    "sector": "Тоғ-кон, геология, металургия саноати",
    "mahsulot": "Саноат вентиляторлар",
    "stend": "Стандарт",
    "area": 9,
    "contact": "Нигматов Шохрух",
    "phone": "99 971 23 08",
    "mapX": 1700,
    "mapY": 260,
    "parent_org_stirs": [
      "200460222"
    ],
    "parent_org_name": "\"O'zmetkombinat\" AJ",
    "tip": "Шатак",
    "supplies_to": [
      "308425864",
      "202328794",
      "311415426",
      "200460222",
      "201204514"
    ],
    "tarmoq": "\"Ўзэлтехсаноат\" уюшмаси",
    "xabardor": "бор",
    "tovar_soni": "40 дан ошиқ вентиляция тизимлари",
    "takliflar_sectors": "\"Ўзтўқимачиликсаноат\" уюшмаси, “O‘zsanoatqurilishmateriallari” uyushmasi, \nFarmatsevtika tarmog‘ini rivojlantirish agentligi",
    "ishtirokchi": "Руртам ака инжинер,  Нигматов Шохрух маркитолог",
    "izoh": "Корхонани камида 50 кв жой керак"
  },
  {
    "id": 44,
    "stir": "204392938",
    "name": "“UZTELMASH” MCHJ",
    "viloyat": "Тошкент шаҳри",
    "tuman": "Яшнобод тумани",
    "sector": "Тоғ-кон, геология, металургия саноати",
    "mahsulot": "Энергетик маҳсулотлар",
    "stend": "Стандарт",
    "area": 9,
    "contact": "",
    "phone": "90 998 67 35",
    "mapX": 1100,
    "mapY": 350,
    "parent_org_stirs": [
      "200460222"
    ],
    "parent_org_name": "\"O'zmetkombinat\" AJ",
    "tip": "Шатак",
    "supplies_to": []
  },
  {
    "id": 45,
    "stir": "312512717",
    "name": "BEKOBOD TOG-KONCHILIK QAYTA ISHLASH KOMBINATI",
    "viloyat": "Тошкент вилояти",
    "tuman": "Бекобод шаҳри",
    "sector": "Тоғ-кон, геология, металургия саноати",
    "mahsulot": "Метал чушкалари",
    "stend": "Стандарт",
    "area": 9,
    "contact": "",
    "phone": "90-9925787",
    "mapX": 1300,
    "mapY": 350,
    "parent_org_stirs": [
      "200460222"
    ],
    "parent_org_name": "\"O'zmetkombinat\" AJ",
    "tip": "Шатак",
    "supplies_to": []
  },
  {
    "id": 46,
    "stir": "302678824",
    "name": "ARTIKUL AZIYA KABEL MCHJ",
    "viloyat": "Тошкент шаҳри",
    "tuman": "Янгиҳаёт тумани",
    "sector": "Тоғ-кон, геология, металургия саноати",
    "mahsulot": "Саноат вентиляторлар",
    "stend": "Стандарт",
    "area": 9,
    "contact": "Нозима",
    "phone": "907881204.0",
    "mapX": 1900,
    "mapY": 170,
    "parent_org_stirs": [
      "308425864",
      "304574612",
      "306918774"
    ],
    "parent_org_name": "НМЗ ТМЗ СМЗ",
    "tip": "НМЗ ТМЗ СМЗ",
    "supplies_to": [
      "306350099"
    ],
    "tarmoq": "\"Ўзэлтехсаноат\" уюшмаси",
    "xabardor": "бор",
    "tovar_soni": "20 хилдан ортиқ кабель-сим маҳсулотлари",
    "takliflar_sectors": "“Navoiy KMK” AJ,\n“Olmaliq KMK” AJ, “O‘zbekiston texnologik metallar kombinati” AJ, “O‘zmetkombinat” AJ, “Navoiyuran” DK",
    "ishtirokchi": "Нозима 99-190-08-88",
    "izoh": "Корхонани хабари бор 12,05,2026 йил куни маҳсулотларни олиб боради"
  },
  {
    "id": 47,
    "stir": "310627455",
    "name": "FORIGHT GRANITE MINE MCHJ XK",
    "viloyat": "Жиззах вилояти",
    "tuman": "Шароф Рашидов тумани",
    "sector": "Тоғ-кон, геология, металургия саноати",
    "mahsulot": "Охак ва охактош маҳсулотлари",
    "stend": "Стандарт",
    "area": 9,
    "contact": "Номозов Шахзод",
    "phone": "97 194 00 43",
    "mapX": 2100,
    "mapY": 170,
    "parent_org_stirs": [
      "308425864",
      "304574612",
      "306918774"
    ],
    "parent_org_name": "НМЗ ТМЗ СМЗ",
    "tip": "НМЗ ТМЗ СМЗ",
    "supplies_to": []
  },
  {
    "id": 48,
    "stir": "300933659",
    "name": "\"NAMANGAN REZINA PLAST\" MCHJ",
    "viloyat": "Наманган вилояти",
    "tuman": "Давлатобод тумани",
    "sector": "Тоғ-кон, геология, металургия саноати",
    "mahsulot": "Резинадан конвеер (транспортёр) тасмалари ва узатма қайишлари (белтинг)",
    "stend": "Стандарт",
    "area": 9,
    "contact": "Боймирзаев Рашид",
    "phone": "97 251 91 11 911770220",
    "mapX": 2300,
    "mapY": 170,
    "parent_org_stirs": [
      "308425864",
      "304574612",
      "306918774"
    ],
    "parent_org_name": "НМЗ ТМЗ СМЗ",
    "tip": "НМЗ ТМЗ СМЗ",
    "supplies_to": []
  },
  {
    "id": 49,
    "stir": "200049541",
    "name": "\"NAMANGANMASH\" MCHJ",
    "viloyat": "Наманган вилояти",
    "tuman": "Наманган шаҳар",
    "sector": "Тоғ-кон, геология, металургия саноати",
    "mahsulot": "Сув насослари ва электр двигателлари",
    "stend": "Стандарт",
    "area": 9,
    "contact": "Убайдуллаев Илхомжон",
    "phone": "91 360 88 28",
    "mapX": 2500,
    "mapY": 170,
    "parent_org_stirs": [
      "308425864",
      "304574612",
      "306918774"
    ],
    "parent_org_name": "НМЗ ТМЗ СМЗ",
    "tip": "НМЗ ТМЗ СМЗ",
    "supplies_to": []
  },
  {
    "id": 50,
    "stir": "304616108",
    "name": "\"NAMELTEX MOTORS\" MCHJ",
    "viloyat": "Наманган вилояти",
    "tuman": "Наманган тумани",
    "sector": "Тоғ-кон, геология, металургия саноати",
    "mahsulot": "Электротехника маҳсулотлари",
    "stend": "Стандарт",
    "area": 9,
    "contact": "Юсупжанов Аъзамжон",
    "phone": "90 640 46 45",
    "mapX": 1900,
    "mapY": 260,
    "parent_org_stirs": [
      "308425864",
      "304574612",
      "306918774"
    ],
    "parent_org_name": "НМЗ ТМЗ СМЗ",
    "tip": "НМЗ ТМЗ СМЗ",
    "supplies_to": []
  },
  {
    "id": 51,
    "stir": "306165146",
    "name": "MANOKIP ZAVODI MCHJ",
    "viloyat": "Тошкент шаҳри",
    "tuman": "Бектемир тумани",
    "sector": "Тоғ-кон, геология, металургия саноати",
    "mahsulot": "Ҳимоя ва бошқарув қурилмаси. Модел: BSU",
    "stend": "Стандарт",
    "area": 9,
    "contact": "",
    "phone": "905446107,  900263032",
    "mapX": 2100,
    "mapY": 260,
    "parent_org_stirs": [
      "308425864",
      "304574612",
      "306918774"
    ],
    "parent_org_name": "НМЗ ТМЗ СМЗ",
    "tip": "НМЗ ТМЗ СМЗ",
    "supplies_to": []
  },
  {
    "id": 52,
    "stir": "309684693",
    "name": "\"SOLAR ENERGY NAVOIY\" MCHJ",
    "viloyat": "Навоий вилояти",
    "tuman": "Навоий шаҳар",
    "sector": "Тоғ-кон, геология, металургия саноати",
    "mahsulot": "Электротехника маҳсулотлари",
    "stend": "Стандарт",
    "area": 9,
    "contact": "Холова Мафтуна Фахриддиновна\nсавдо бўлими бошлиғи",
    "phone": "931495775.0",
    "mapX": 2300,
    "mapY": 260,
    "parent_org_stirs": [
      "308425864",
      "304574612",
      "306918774"
    ],
    "parent_org_name": "НМЗ ТМЗ СМЗ",
    "tip": "НМЗ ТМЗ СМЗ",
    "supplies_to": [
      "201204514",
      "308425864",
      "200002933",
      "310622519"
    ],
    "tarmoq": "Ўзбекистон Савдо-саноат палатаси",
    "xabardor": "ха",
    "tovar_soni": "Қёш панели сув иситгич ва мини шамол генератори",
    "takliflar_sectors": "",
    "ishtirokchi": "",
    "izoh": "Эртага тайёрлаб беради кимлар иштирок этишини"
  },
  {
    "id": 53,
    "stir": "313003906",
    "name": "«STEELPRO ENGINEERING»  MCHJ",
    "viloyat": "Тошкент вилояти",
    "tuman": "Шайхонтоҳур тумани",
    "sector": "Sanoat",
    "mahsulot": "Подшипник корпуси, Колесо",
    "stend": "Стандарт",
    "area": 9,
    "contact": "Улуғбек Эрматов",
    "phone": "94-215-01-04,  50-000-77-88",
    "mapX": 2500,
    "mapY": 260,
    "parent_org_stirs": [
      "308425864",
      "304574612",
      "306918774"
    ],
    "parent_org_name": "НМЗ ТМЗ СМЗ",
    "tip": "НМЗ ТМЗ СМЗ",
    "supplies_to": []
  },
  {
    "id": 54,
    "stir": "301293054",
    "name": "\"NADIR RABER\" XK",
    "viloyat": "Тошкент шаҳри",
    "tuman": "Шайхонтоҳур тумани",
    "sector": "Тоғ-кон, геология, металургия саноати",
    "mahsulot": "Резина клинли ременлар",
    "stend": "Стандарт",
    "area": 9,
    "contact": "Рихсиев Н.Н.",
    "phone": "99-824-70-44",
    "mapX": 1900,
    "mapY": 350,
    "parent_org_stirs": [
      "308425864",
      "304574612",
      "306918774"
    ],
    "parent_org_name": "НМЗ ТМЗ СМЗ",
    "tip": "НМЗ ТМЗ СМЗ",
    "supplies_to": []
  },
  {
    "id": 55,
    "stir": "304951239",
    "name": "“ZHONGTIAN CHEMICAL QK” MChJ",
    "viloyat": "Тошкент вилояти",
    "tuman": "Оҳангарон тумани",
    "sector": "Sanoat",
    "mahsulot": "Кимё реагентлар",
    "stend": "Стандарт",
    "area": 9,
    "contact": "Эрматов Алибек",
    "phone": "881527777.0",
    "mapX": 2100,
    "mapY": 350,
    "parent_org_stirs": [
      "308425864",
      "304574612",
      "306918774"
    ],
    "parent_org_name": "НМЗ ТМЗ СМЗ",
    "tip": "НМЗ ТМЗ СМЗ",
    "supplies_to": [
      "308425864"
    ],
    "tarmoq": "\"Ўзкимёсаноат\" АЖ",
    "xabardor": "ха",
    "tovar_soni": "10",
    "takliflar_sectors": "Эрматов Алибек",
    "ishtirokchi": "Директор ва технолог",
    "izoh": "Ўзкимёсаноат АЖ таркибида қатнашади 11 май куни маҳсулотларни етказади"
  },
  {
    "id": 56,
    "stir": "300848161",
    "name": "\"KRANTAS\" MCHJ",
    "viloyat": "Тошкент шаҳри",
    "tuman": "Мирзо Улуғбек тумани",
    "sector": "Тоғ-кон, геология, металургия саноати",
    "mahsulot": "Ярим тиркама бензин ташувчи ППCН-40м³, Автокран 25-100 тонна",
    "stend": "Эксклюзив",
    "area": 9,
    "contact": "Нуритдин",
    "phone": "90 330 00 00",
    "mapX": 50,
    "mapY": 700,
    "parent_org_stirs": [],
    "parent_org_name": "Hududiy korxonalar",
    "tip": "Ҳудудий корхоналар",
    "supplies_to": []
  },
  {
    "id": 57,
    "stir": "303784114",
    "name": "“SURXON ART KERAMIKS” MCHJ",
    "viloyat": "Сурхондарё вилояти",
    "tuman": "Термиз тумани",
    "sector": "Тоғ-кон, геология, металургия саноати",
    "mahsulot": "Оловбардош ғишт маҳсулотлари",
    "stend": "Стандарт",
    "area": 9,
    "contact": "Очилдиев Ғайрат Хайдарович",
    "phone": "99-733-88-03",
    "mapX": 400,
    "mapY": 700,
    "parent_org_stirs": [],
    "parent_org_name": "Hududiy korxonalar",
    "tip": "Ҳудудий корхоналар",
    "supplies_to": []
  },
  {
    "id": 58,
    "stir": "307225283",
    "name": "\"MYSTEP\" MCHJ",
    "viloyat": "Фарғона вилояти",
    "tuman": "Марғилон шаҳар",
    "sector": "Тоғ-кон, геология, металургия саноати",
    "mahsulot": "Махсус оёқ кийимлар",
    "stend": "Стандарт",
    "area": 9,
    "contact": "Хамдамов Тохиржон Баходиржон Ўғли",
    "phone": "(99) 398-20-20",
    "mapX": 750,
    "mapY": 700,
    "parent_org_stirs": [],
    "parent_org_name": "Hududiy korxonalar",
    "tip": "Ҳудудий корхоналар",
    "supplies_to": [],
    "tarmoq": "\"Ўзчармсаноат\" уюшмаси",
    "xabardor": "",
    "tovar_soni": "",
    "takliflar_sectors": "Xamdamov Toxirjon Baxodirjon O‘g‘li",
    "ishtirokchi": "",
    "izoh": "Телефон рақами хато экан, умуман бу корхонага алоқаси йўқ, Наманганлик фуқаро экан."
  },
  {
    "id": 59,
    "stir": "301353754",
    "name": "\"SALAMAN S ROLIKS\" MCHJ",
    "viloyat": "Фарғона вилояти",
    "tuman": "Марғилон шаҳар",
    "sector": "Тоғ-кон, геология, металургия саноати",
    "mahsulot": "Махсус оёқ кийимлар",
    "stend": "Стандарт",
    "area": 9,
    "contact": "Маматханов Саидкамолхон Умарханович",
    "phone": "(93) 736-80-00",
    "mapX": 1100,
    "mapY": 700,
    "parent_org_stirs": [],
    "parent_org_name": "Hududiy korxonalar",
    "tip": "Ҳудудий корхоналар",
    "supplies_to": [
      "308425864"
    ],
    "tarmoq": "\"Ўзчармсаноат\" уюшмаси",
    "xabardor": "Bor",
    "tovar_soni": "40 xildan ortiq",
    "takliflar_sectors": "OKMK, Yo'l qurilish, O'zbekko'mir, IES, Suvta'minot, obodonlashtirish, Navoiyazot, Navoiyuran",
    "ishtirokchi": "Brokker va xodimlar",
    "izoh": "Spets obuv"
  },
  {
    "id": 60,
    "stir": "205195184",
    "name": "\"OSIYO BAZIS\" XK",
    "viloyat": "Фарғона вилояти",
    "tuman": "Марғилон шаҳар",
    "sector": "Тоғ-кон, геология, металургия саноати",
    "mahsulot": "Махсус иш кийимлари",
    "stend": "Стандарт",
    "area": 9,
    "contact": "Аскарходжаев Кахрамон Абдумуталибович",
    "phone": "(93)648-62-02",
    "mapX": 1450,
    "mapY": 700,
    "parent_org_stirs": [],
    "parent_org_name": "Hududiy korxonalar",
    "tip": "Ҳудудий корхоналар",
    "supplies_to": []
  },
  {
    "id": 61,
    "stir": "307083177",
    "name": "\"DAVR GEO TEX\" MCHJ",
    "viloyat": "Самарқанд вилояти",
    "tuman": "Қўшработ тумани",
    "sector": "Тоғ-кон, геология, металургия саноати",
    "mahsulot": "Бурғулаш ускуналари",
    "stend": "Стандарт",
    "area": 9,
    "contact": "Хамдамов Нодирбек Хамзакулович",
    "phone": "(99-458-82-08)",
    "mapX": 1800,
    "mapY": 700,
    "parent_org_stirs": [],
    "parent_org_name": "Hududiy korxonalar",
    "tip": "Ҳудудий корхоналар",
    "supplies_to": []
  },
  {
    "id": 62,
    "stir": "304951239",
    "name": "“ZHONGTIAN CHEMICAL QK” MChJ",
    "viloyat": "Тошкент вилояти",
    "tuman": "Оҳангарон тумани",
    "sector": "Sanoat",
    "mahsulot": "Кимё реагентлар",
    "stend": "Стандарт",
    "area": 9,
    "contact": "Эрматов Алибек",
    "phone": "881527777.0",
    "mapX": 2150,
    "mapY": 700,
    "parent_org_stirs": [],
    "parent_org_name": "Hududiy korxonalar",
    "tip": "Ҳудудий корхоналар",
    "supplies_to": [
      "308425864"
    ],
    "tarmoq": "\"Ўзкимёсаноат\" АЖ",
    "xabardor": "ха",
    "tovar_soni": "10",
    "takliflar_sectors": "Эрматов Алибек",
    "ishtirokchi": "Директор ва технолог",
    "izoh": "Ўзкимёсаноат АЖ таркибида қатнашади 11 май куни маҳсулотларни етказади"
  },
  {
    "id": 63,
    "stir": "307489668",
    "name": "\"KATTAQO'RG'ON ELEKTROTEXNIKAZAVODI\" MCHJ",
    "viloyat": "Самарқанд вилояти",
    "tuman": "Каттақўрғон тумани",
    "sector": "Тоғ-кон, геология, металургия саноати",
    "mahsulot": "Электротехника маҳсулотлари",
    "stend": "Стандарт",
    "area": 9,
    "contact": "Норбоев Анвар",
    "phone": "93 555 10 24,  93 555 10 26",
    "mapX": 2500,
    "mapY": 700,
    "parent_org_stirs": [],
    "parent_org_name": "Hududiy korxonalar",
    "tip": "Ҳудудий корхоналар",
    "supplies_to": []
  },
  {
    "id": 64,
    "stir": "301455722",
    "name": "\"BISYOR FAYZ\" MCHJ",
    "viloyat": "Хоразм вилояти",
    "tuman": "Урганч шаҳри",
    "sector": "Тоғ-кон, геология, металургия саноати",
    "mahsulot": "Чўян маҳсулотлари",
    "stend": "Стандарт",
    "area": 9,
    "contact": "Нодирбек",
    "phone": "951799000.0",
    "mapX": 50,
    "mapY": 770,
    "parent_org_stirs": [],
    "parent_org_name": "Hududiy korxonalar",
    "tip": "Ҳудудий корхоналар",
    "supplies_to": []
  },
  {
    "id": 65,
    "stir": "302681014",
    "name": "GRAND METALL STROY MCHJ",
    "viloyat": "Тошкент шаҳри",
    "tuman": "Олмазор тумани",
    "sector": "Тоғ-кон, геология, металургия саноати",
    "mahsulot": "Кўприкли ва чорпоя кўтарма кранлар",
    "stend": "Эксклюзив",
    "area": 36,
    "contact": "",
    "phone": "998 87 011 99 77",
    "mapX": 400,
    "mapY": 770,
    "parent_org_stirs": [],
    "parent_org_name": "Hududiy korxonalar",
    "tip": "Ҳудудий корхоналар",
    "supplies_to": []
  },
  {
    "id": 66,
    "stir": "307346759",
    "name": "“AFNAN BUILDING 2020” MCHJ",
    "viloyat": "Наманган вилояти",
    "tuman": "Наманган шаҳар",
    "sector": "Тоғ-кон, геология, металургия саноати",
    "mahsulot": "Синтетик материаллардан тайёрланган, электр монтерлари учун химоя белбоғи (пояс)",
    "stend": "Стандарт",
    "area": 9,
    "contact": "",
    "phone": "913682126.0",
    "mapX": 750,
    "mapY": 770,
    "parent_org_stirs": [],
    "parent_org_name": "Hududiy korxonalar",
    "tip": "Ҳудудий корхоналар",
    "supplies_to": []
  },
  {
    "id": 67,
    "stir": "306261423",
    "name": "“METALL REAL” xususiy korxonasi",
    "viloyat": "Бухоро вилояти",
    "tuman": "Ғиждувон тумани",
    "sector": "Тоғ-кон, геология, металургия саноати",
    "mahsulot": "Бурғилаш дастгоҳлари, майдалагич насослари, тегирмонлар, юклаш ва етказиб бериш ускуналари учун эҳтиёт қисмлар",
    "stend": "Стандарт",
    "area": 9,
    "contact": "Шаропов Мухтор",
    "phone": "90-744-62-91",
    "mapX": 1100,
    "mapY": 770,
    "parent_org_stirs": [],
    "parent_org_name": "Hududiy korxonalar",
    "tip": "Ҳудудий корхоналар",
    "supplies_to": []
  },
  {
    "id": 68,
    "stir": "205442913",
    "name": "\"KOGONTEKS\" МЧЖ",
    "viloyat": "Бухоро вилояти",
    "tuman": "Когон тумани",
    "sector": "Тоғ-кон, геология, металургия саноати",
    "mahsulot": "Насослар, технологик ускуналар, печлар, тегирмонлар учун эҳтиёт қисмлар",
    "stend": "Стандарт",
    "area": 9,
    "contact": "Худойқулов Давлат Худойназарович",
    "phone": "90-715-33-36",
    "mapX": 1450,
    "mapY": 770,
    "parent_org_stirs": [],
    "parent_org_name": "Hududiy korxonalar",
    "tip": "Ҳудудий корхоналар",
    "supplies_to": [],
    "tarmoq": "\"Ўзтўқимачиликсаноат\" уюшмаси",
    "xabardor": "Bor",
    "tovar_soni": "",
    "takliflar_sectors": "Худойқулов Давлат Худойназарович",
    "ishtirokchi": "",
    "izoh": "Телефон олмади"
  },
  {
    "id": 69,
    "stir": "201962284",
    "name": "“SREDAZSVETMETENERGO” AJ",
    "viloyat": "Тошкент шаҳри",
    "tuman": "Шайхонтоҳур тумани",
    "sector": "Тоғ-кон, геология, металургия саноати",
    "mahsulot": "Иссиқлик-энергетика ускуналарини лойиҳалаш, тайёрлаш, монтаж қилиш",
    "stend": "Стандарт",
    "area": 18,
    "contact": "",
    "phone": "977551311.0",
    "mapX": 1800,
    "mapY": 770,
    "parent_org_stirs": [],
    "parent_org_name": "Hududiy korxonalar",
    "tip": "Ҳудудий корхоналар",
    "supplies_to": []
  },
  {
    "id": 70,
    "stir": "308952226",
    "name": "\"INOPROM\" MCHJ",
    "viloyat": "Тошкент шаҳри",
    "tuman": "Чилонзор тумани",
    "sector": "Sanoat",
    "mahsulot": "Реагенты-собиратели, Реагенты-пенообразователи, Реагенты-флокулянты",
    "stend": "Стандарт",
    "area": 9,
    "contact": "Казин Игорь Александрович",
    "phone": "99 849  88 88",
    "mapX": 2150,
    "mapY": 770,
    "parent_org_stirs": [],
    "parent_org_name": "Hududiy korxonalar",
    "tip": "Ҳудудий корхоналар",
    "supplies_to": []
  },
  {
    "id": 71,
    "stir": "300958800",
    "name": "\"NOSIRXON MUSLIM\" MCHJ",
    "viloyat": "Тошкент шаҳри",
    "tuman": "Чилонзор тумани",
    "sector": "Sanoat",
    "mahsulot": "Алюминиевые, компазинтые панели",
    "stend": "Стандарт",
    "area": 9,
    "contact": "Залина",
    "phone": "+998 99 011 90 90",
    "mapX": 2500,
    "mapY": 770,
    "parent_org_stirs": [],
    "parent_org_name": "Hududiy korxonalar",
    "tip": "Ҳудудий корхоналар",
    "supplies_to": []
  },
  {
    "id": 72,
    "stir": "307776556",
    "name": "\"NAVOIYSKIY ZAVOD BUROVOY TEXNIKI\" MCHJ",
    "viloyat": "Навоий вилояти",
    "tuman": "Навоий шаҳар",
    "sector": "Тоғ-кон, геология, металургия саноати",
    "mahsulot": "Бурғулаш ускуналари",
    "stend": "Стандарт",
    "area": 18,
    "contact": "Рузиев Дилшод",
    "phone": "97 377 00 00",
    "mapX": 50,
    "mapY": 840,
    "parent_org_stirs": [],
    "parent_org_name": "Hududiy korxonalar",
    "tip": "Ҳудудий корхоналар",
    "supplies_to": []
  },
  {
    "id": 73,
    "stir": "309986894",
    "name": "“METALL-TECHNOLOGIES” MChJ",
    "viloyat": "Бухоро вилояти",
    "tuman": "Ғиждувон тумани",
    "sector": "Тоғ-кон, геология, металургия саноати",
    "mahsulot": "Тоғ-кон, нефтгаз, кимё, энергетика соҳаларида ишлатиладиган йирик ҳажмдаги элаш, ажратиш, майдалаш, ювиш ускуналари учун эҳтиёт қисмлар",
    "stend": "Стандарт",
    "area": 9,
    "contact": "Ҳасанов Шохрух Зокир ўғли  (Ҳусен ака)",
    "phone": "91-253-88-00",
    "mapX": 400,
    "mapY": 840,
    "parent_org_stirs": [],
    "parent_org_name": "Hududiy korxonalar",
    "tip": "Ҳудудий корхоналар",
    "supplies_to": []
  },
  {
    "id": 74,
    "stir": "306777175",
    "name": "“PROM TEX EKSPERTIZA” MCHJ",
    "viloyat": "Тошкент шаҳри",
    "tuman": "Юнусобод тумани",
    "sector": "Sanoat",
    "mahsulot": "Саноат хавфсизлиги экспертизаси утказиш",
    "stend": "Стандарт",
    "area": 9,
    "contact": "Гайрат",
    "phone": "97-368-74-04",
    "mapX": 750,
    "mapY": 840,
    "parent_org_stirs": [],
    "parent_org_name": "Hududiy korxonalar",
    "tip": "Ҳудудий корхоналар",
    "supplies_to": []
  },
  {
    "id": 75,
    "stir": "310132645",
    "name": "“ARF-RTI” MCHJ",
    "viloyat": "Тошкент шаҳри",
    "tuman": "Сергели тумани",
    "sector": "Sanoat",
    "mahsulot": "Конвеер ролик",
    "stend": "Стандарт",
    "area": 9,
    "contact": "",
    "phone": "97-100-93-54, 33-363-63-60",
    "mapX": 1100,
    "mapY": 840,
    "parent_org_stirs": [],
    "parent_org_name": "Hududiy korxonalar",
    "tip": "Ҳудудий корхоналар",
    "supplies_to": []
  },
  {
    "id": 76,
    "stir": "303287463",
    "name": "“GEOBURTEHNIKA” XK MCHJ",
    "viloyat": "Тошкент шаҳри",
    "tuman": "Олмазор тумани",
    "sector": "Sanoat",
    "mahsulot": "Ностандарт ва кон-геологик қидирув бургулаш асбобларини",
    "stend": "Стандарт",
    "area": 9,
    "contact": "Сотув менеджери Фатхуллаев Зиёвуддин",
    "phone": "94 662 68 33",
    "mapX": 1450,
    "mapY": 840,
    "parent_org_stirs": [],
    "parent_org_name": "Hududiy korxonalar",
    "tip": "Ҳудудий корхоналар",
    "supplies_to": []
  },
  {
    "id": 77,
    "stir": "302776924",
    "name": "ATMZ",
    "viloyat": "Тошкент шаҳри",
    "tuman": "Яшнобод тумани",
    "sector": "Sanoat",
    "mahsulot": "Выключатель рудничный ВРН 250А, Выключатель рудничный ВРН-200А, Пускатель рудничный ПРН-63М 56А, Пускатели рудничный электромагнитные",
    "stend": "Стандарт",
    "area": 9,
    "contact": "",
    "phone": "977201071, 943790565",
    "mapX": 1800,
    "mapY": 840,
    "parent_org_stirs": [],
    "parent_org_name": "Hududiy korxonalar",
    "tip": "Ҳудудий корхоналар",
    "supplies_to": []
  },
  {
    "id": 78,
    "stir": "312635444",
    "name": "“ANGREN ELEKTRO PROM” QK",
    "viloyat": "Тошкент вилояти",
    "tuman": "Ангрен шаҳри",
    "sector": "Sanoat",
    "mahsulot": "Электродлар (қопланган пайвандлаш электродлари), Пайвандлаш сими, Зангламас метал электроди",
    "stend": "Стандарт",
    "area": 9,
    "contact": "Б.Ахмедов",
    "phone": "936037000.0",
    "mapX": 2150,
    "mapY": 840,
    "parent_org_stirs": [],
    "parent_org_name": "Hududiy korxonalar",
    "tip": "Ҳудудий корхоналар",
    "supplies_to": []
  },
  {
    "id": 79,
    "stir": "300439149",
    "name": "“KOGON MARS PLYUS ” MChJ",
    "viloyat": "Бухоро вилояти",
    "tuman": "Ғиждувон тумани",
    "sector": "Тоғ-кон, геология, металургия саноати",
    "mahsulot": "Тоғ-кон, нефтгаз, кимё, энергетика соҳалари учун эҳтиёт қисмлар (клапанлар, бурғулаш эҳтиёт қисмлари, ротатсион гидравлик ва пневматик двигателлар жихозлари в.б)",
    "stend": "Стандарт",
    "area": 9,
    "contact": "Касимов Сайёт, Антонов Александр",
    "phone": "998-91-241-44-88, 998-99-946-18-48",
    "mapX": 2500,
    "mapY": 840,
    "parent_org_stirs": [],
    "parent_org_name": "Hududiy korxonalar",
    "tip": "Ҳудудий корхоналар",
    "supplies_to": []
  },
  {
    "id": 80,
    "stir": "303160314",
    "name": "LEGO GROUP",
    "viloyat": "Самарқанд вилояти",
    "tuman": "Қўшработ тумани",
    "sector": "Sanoat",
    "mahsulot": "Тоғ-кон саноати ҳамда геологик изланишларда қўлланиладиган бурғулаш воситалари ва уларнинг эҳтиёт қисмлари",
    "stend": "Стандарт",
    "area": 9,
    "contact": "МУСУРМОНОВ ОЙБЕК ТЎРАБОЙ ЎҒЛИ",
    "phone": "(97-920-71-30)",
    "mapX": 50,
    "mapY": 910,
    "parent_org_stirs": [],
    "parent_org_name": "Hududiy korxonalar",
    "tip": "Ҳудудий корхоналар",
    "supplies_to": []
  },
  {
    "id": 81,
    "stir": "310341100",
    "name": "\"CEMIX\" MCHJ",
    "viloyat": "Самарқанд вилояти",
    "tuman": "Нуробод тумани",
    "sector": "Sanoat",
    "mahsulot": "1001 CALCIUM CARBONATE 1-2-3-5 MICRON, 8282 OQ PLITKA YELIMI FLEX",
    "stend": "Стандарт",
    "area": 9,
    "contact": "Пулатов Мухаммад",
    "phone": "998-77-363-68-98",
    "mapX": 400,
    "mapY": 910,
    "parent_org_stirs": [],
    "parent_org_name": "Hududiy korxonalar",
    "tip": "Ҳудудий корхоналар",
    "supplies_to": [],
    "tarmoq": "\"Ўзсаноатқурилишматериаллари\" уюшмаси",
    "xabardor": "ха",
    "tovar_soni": "Грунтовка клей \nшпатклевка (цемент таркибли) краска",
    "takliflar_sectors": "ишламайди",
    "ishtirokchi": "Мухаммад\nхудудий сотув менеджери",
    "izoh": "Сешанба куни тўлиқ маълумот берилди"
  },
  {
    "id": 82,
    "stir": "304096534",
    "name": "\"GOLD SHARQ SIFAT\" MCHJ",
    "viloyat": "Самарқанд вилояти",
    "tuman": "Пастдарғом тумани",
    "sector": "Sanoat",
    "mahsulot": "Конвейр ленталар, Резина гранулалари, Хом резиналар",
    "stend": "Стандарт",
    "area": 9,
    "contact": "Асроров Дамиржон Орзиқулович",
    "phone": "(97-286-67-57)",
    "mapX": 750,
    "mapY": 910,
    "parent_org_stirs": [],
    "parent_org_name": "Hududiy korxonalar",
    "tip": "Ҳудудий корхоналар",
    "supplies_to": []
  },
  {
    "id": 83,
    "stir": "308852793",
    "name": "\"SHELF VOSTOK\" МCHJ QK",
    "viloyat": "Самарқанд вилояти",
    "tuman": "Жомбой тумани",
    "sector": "Sanoat",
    "mahsulot": "Бошқа металл цистерна, резервуар ва контейнерлар ишлаб чиқариш",
    "stend": "Стандарт",
    "area": 9,
    "contact": "Ибрагимов Жахонгир Азамахунович",
    "phone": "(97-160-30-00)",
    "mapX": 1100,
    "mapY": 910,
    "parent_org_stirs": [],
    "parent_org_name": "Hududiy korxonalar",
    "tip": "Ҳудудий корхоналар",
    "supplies_to": []
  },
  {
    "id": 84,
    "stir": "205128867",
    "name": "\"SPZ-BEARINGS\" MCHJ",
    "viloyat": "Андижон вилояти",
    "tuman": "Жалолқудуқ тумани",
    "sector": "Sanoat",
    "mahsulot": "Железнодорожный подшипник 36-42726 Е2М, Цельнокатаное колесо",
    "stend": "Эксклюзив",
    "area": 18,
    "contact": "Азим",
    "phone": "99 911 99 19, 99 002 00 41",
    "mapX": 1450,
    "mapY": 910,
    "parent_org_stirs": [],
    "parent_org_name": "Hududiy korxonalar",
    "tip": "Ҳудудий корхоналар",
    "supplies_to": []
  },
  {
    "id": 85,
    "stir": "306541589",
    "name": "“TAI CHANG SPECIAL STEEL” МЧЖ ХК (NMZ)",
    "viloyat": "Наманган вилояти",
    "tuman": "-",
    "sector": "Sanoat",
    "mahsulot": "А-400 синфидаги-10,12,14,16,18,20,22,25 мм ўлчамдаги Арматуралар, А-400 синфидаги-5,5, 6,5, 8. мм  ўлчамдаги Катанка Симлар",
    "stend": "Стандарт",
    "area": 25,
    "contact": "",
    "phone": "99 970 88 08, 95 155 26 46",
    "mapX": 1800,
    "mapY": 910,
    "parent_org_stirs": [],
    "parent_org_name": "Hududiy korxonalar",
    "tip": "Ҳудудий корхоналар",
    "supplies_to": []
  },
  {
    "id": 86,
    "stir": "312665811",
    "name": "\"APEX TOOLS\" MCHJ",
    "viloyat": "Тошкент вилояти",
    "tuman": "Олмалиқ шаҳри",
    "sector": "Sanoat",
    "mahsulot": "Долото PDC, Долото трехшарошечное",
    "stend": "Стандарт",
    "area": 9,
    "contact": "",
    "phone": "998-90-174-39-31",
    "mapX": 2150,
    "mapY": 910,
    "parent_org_stirs": [],
    "parent_org_name": "Hududiy korxonalar",
    "tip": "Ҳудудий корхоналар",
    "supplies_to": []
  },
  {
    "id": 87,
    "stir": "302821203",
    "name": "STARTMIX",
    "viloyat": "Хоразм вилояти",
    "tuman": "Урганч шаҳри",
    "sector": "Sanoat",
    "mahsulot": "Тоғ-кон саноати ва ер ости конлари учун махсус техникалар",
    "stend": "Стандарт",
    "area": 9,
    "contact": "",
    "phone": "998-90-174-39-31",
    "mapX": 2500,
    "mapY": 910,
    "parent_org_stirs": [],
    "parent_org_name": "Hududiy korxonalar",
    "tip": "Ҳудудий корхоналар",
    "supplies_to": []
  },
  {
    "id": 88,
    "stir": "301374254",
    "name": "AZIA METALL PROF MCHJ QK",
    "viloyat": "Самарқанд вилояти",
    "tuman": "Самарқанд шаҳри",
    "sector": "Sanoat",
    "mahsulot": "Темир рулон, Труба",
    "stend": "Стандарт",
    "area": 25,
    "contact": "Ш.Солаев",
    "phone": "998 97 137 03 04",
    "mapX": 50,
    "mapY": 980,
    "parent_org_stirs": [],
    "parent_org_name": "Hududiy korxonalar",
    "tip": "Ҳудудий корхоналар",
    "supplies_to": []
  },
  {
    "id": 89,
    "stir": "305118282",
    "name": "WORLD TRADING COMPANY MCHJ  QK",
    "viloyat": "Жиззах вилояти",
    "tuman": "Пахтакор тумани",
    "sector": "Sanoat",
    "mahsulot": "Юк ва енгил автомобиллар учун антифриз, Ҳаво филтьрлари",
    "stend": "Стандарт",
    "area": 9,
    "contact": "Ибрагимов Зайниддин",
    "phone": "99-803-94-94",
    "mapX": 400,
    "mapY": 980,
    "parent_org_stirs": [],
    "parent_org_name": "Hududiy korxonalar",
    "tip": "Ҳудудий корхоналар",
    "supplies_to": []
  },
  {
    "id": 90,
    "stir": "",
    "name": "\"O'ZBEKXIMMASH\" AJ",
    "viloyat": "",
    "tuman": "",
    "sector": "Sanoat",
    "mahsulot": "",
    "stend": "Eksklyuziv",
    "area": 36,
    "contact": "Аида",
    "phone": "99 400 14 15",
    "mapX": 750,
    "mapY": 980,
    "parent_org_stirs": [],
    "parent_org_name": "",
    "tip": "",
    "supplies_to": []
  },
  {
    "id": 91,
    "stir": "",
    "name": "TEXNOPARK",
    "viloyat": "",
    "tuman": "",
    "sector": "Sanoat",
    "mahsulot": "",
    "stend": "Eksklyuziv",
    "area": 36,
    "contact": "Махмуд",
    "phone": "93 566 10 12",
    "mapX": 1100,
    "mapY": 980,
    "parent_org_stirs": [],
    "parent_org_name": "",
    "tip": "",
    "supplies_to": []
  },
  {
    "id": 92,
    "stir": "200897524",
    "name": "TOSHKENT TRUBA ZAVODI MCHJ QK",
    "viloyat": "Тошкент шаҳри",
    "tuman": "Шайхонтоҳур тумани",
    "sector": "Sanoat",
    "mahsulot": "Қувурлар, арматура, катанка, сим, маҳкамлагичлар",
    "stend": "Эксклюзив",
    "area": 36,
    "contact": "Махмуд",
    "phone": "93 566 10 12",
    "mapX": 1450,
    "mapY": 980,
    "parent_org_stirs": [],
    "parent_org_name": "Hududiy korxonalar",
    "tip": "Ҳудудий корхоналар",
    "supplies_to": []
  },
  {
    "id": 93,
    "stir": "202328794",
    "name": "\"Navoiy KMK\" AJ",
    "viloyat": "Navoiy viloyati",
    "tuman": "Navoiy shahri",
    "sector": "Tog'-kon, geologiya, metalurgiya sanoati",
    "mahsulot": "",
    "stend": "Standart",
    "area": 0,
    "contact": "",
    "phone": "",
    "mapX": 0,
    "mapY": 0,
    "parent_org_name": "\"Navoiy KMK\" AJ",
    "parent_org_stirs": [
      "202328794"
    ],
    "self_stirs": [
      "202328794"
    ],
    "tip": "",
    "supplies_to": []
  },
  {
    "id": 94,
    "stir": "308425864",
    "name": "\"Olmaliq KMK\" AJ",
    "viloyat": "Toshkent viloyati",
    "tuman": "Olmaliq shahri",
    "sector": "Tog'-kon, geologiya, metalurgiya sanoati",
    "mahsulot": "",
    "stend": "Standart",
    "area": 0,
    "contact": "",
    "phone": "",
    "mapX": 0,
    "mapY": 0,
    "parent_org_name": "\"Olmaliq KMK\" AJ",
    "parent_org_stirs": [
      "308425864"
    ],
    "self_stirs": [
      "308425864"
    ],
    "tip": "",
    "supplies_to": []
  },
  {
    "id": 95,
    "stir": "200460222",
    "name": "\"O'zmetkombinat\" AJ",
    "viloyat": "Toshkent viloyati",
    "tuman": "Bekobod shahri",
    "sector": "Tog'-kon, geologiya, metalurgiya sanoati",
    "mahsulot": "",
    "stend": "Standart",
    "area": 0,
    "contact": "",
    "phone": "",
    "mapX": 0,
    "mapY": 0,
    "parent_org_name": "\"O'zmetkombinat\" AJ",
    "parent_org_stirs": [
      "200460222"
    ],
    "self_stirs": [
      "200460222"
    ],
    "tip": "",
    "supplies_to": []
  },
  {
    "id": 96,
    "stir": "304574612",
    "name": "НМЗ ТМЗ СМЗ",
    "viloyat": "",
    "tuman": "",
    "sector": "Tog'-kon, geologiya, metalurgiya sanoati",
    "mahsulot": "",
    "stend": "Standart",
    "area": 0,
    "contact": "",
    "phone": "",
    "mapX": 0,
    "mapY": 0,
    "parent_org_name": "НМЗ ТМЗ СМЗ",
    "parent_org_stirs": [
      "308425864",
      "304574612",
      "306918774"
    ],
    "self_stirs": [
      "308425864",
      "304574612",
      "306918774"
    ],
    "tip": "",
    "supplies_to": []
  }
];